

INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (1, '2GO Group, Inc.', '15th Floor, Times Plaza Building
United Nations Avenue corner Taft Avenue
Ermita, Manila 1000, Philippines', 'investor_relations@2go.com.ph', '(02) 528-7000');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (2, '8990 Holdings, Inc.', '2nd Flr. PGMC Bldg. 76 Calbayog cor. DM Guevarra St., Mandaluyong City,Philippines', 'house@8990holdings.com', '+63-2-533-3915 | +63-2-533-3917');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (3, 'A Brown Company, Inc.', 'Suite 3301-A West Tower,
Philippine Stock Exchange Building Exchange
Road, Pasig City', ' abci_gmml@cdo.philcom.com', '+63 2 633-3135');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (4, 'A. Soriano Corporation', '7th Floor Pacific Star Building,
Makati Ave. cor Gil Puyat Ave. Ext.,
1209 Makati City, Philippines', ' asoriano@globe.com.ph', '+63.2.819-0251 to 60');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (5, 'ABS-CBN Corporation', 'Sgt. E.A. Esguerra Avenue
Quezon City Philippines 1103 ', 'IR@abs-cbn.com', '(+632) 415-2272');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (6, 'ABS-CBN Holdings Corporation', 'Sgt. E.A. Esguerra Avenue
Quezon City Philippines 1103 ', null, '+63 (2) 631 8024 local 6151-6155');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (7, 'AG Finance, Incorporated', '4th Floor Citibank Center Paseo De Roxas, Makati City', 'service@agfinance.ph', null);
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (8, 'APC Group, Inc.', 'G/F MyTown New York Building, General E. Jacinto St. corner Capas St., Brgy Guadalupe Nuevo, Makati City', 'info@apcgroupinc.com', '(623) 266-4159');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (9, 'ATN Holdings, Inc.', '9/F Summit One Tower, 530 Shaw Boulevard, Mandaluyong City 1501', 'tbgi@tbgi.net.ph', '7170523.0');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (10, 'AbaCore Capital Holdings, Inc.', 'No. 28 N. Domingo St. near corner Gilmore St., New Manila, Quezon City', 'abacorecapital@yahoo.com.ph', '724-5055');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (11, 'Aboitiz Equity Ventures, Inc.', 'NAC Tower, 32nd Street 
Bonifacio Global City 
Taguig City 1634 
Metro Manila, Philippines ', 'erwin.jallorina@aboitiz.com ', '(632) 886-2800');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (12, 'Aboitiz Power Corporation', 'NAC Tower, 32nd Street 
Bonifacio Global City 
Taguig City 1634 
Metro Manila, Philippines ', 'roman.azanza@aboitiz.com ', '(632) 886-2800');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (13, 'Abra Mining and Industrial Corporation', 'Suite 3, 3/F Jafer Building 118 West Avenue, Quezon City 1104', 'amic@netasia.net', '925-1605 to 08');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (14, 'Acesite (Phils.) Hotel Corporation', 'Room 610, Manila Pavilion Hotel, United Nations Ave. cor. M. Orosa St., Ermita, Manila 1000', 'r.ricardo@manilapavilion.com.ph', '(02) 526 6211');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (15, 'AgriNurture, Inc.', 'Unit 111 Cedar Mansions II, #7 Escriva Drive, Ortigas Center, Barangay San Antonio, Pasig City', 'lisette.arboleda@ani.com.ph', '044-8156340');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (16, 'Alliance Global Group, Inc.', '7/F 1880 Eastwood Avenue, Eastwood City CyberPark, Bagumbayan, Quezon City', ' dina_inting@allianceglobal.biz', '709-2038 to 40');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (17, 'Alliance Select Foods International, Inc.', 'Unit 1206, East Tower, Philippine Stock Exchange Centre, Exchange Road, Ortigas Center, Pasig City', 'kpambrocio@allianceselectfoods.com', '(02) 6355241-44');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (18, 'Allied Banking Corporation', 'Allied Bank Centre, 6754 Ayala Ave. Makati City', 'info@alliedbank.com.ph', '8102451.0');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (19, 'Alsons Consolidated Resources, Inc.', 'Alsons Bldg., 2286 Chino Roces Ave., Makati City', ' legal@alcantaragroup.com', '02-982-3000');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (20, 'Anchor Land Holdings, Inc.', 'Unit 11-B, 11th Floor, L.V. Locsin Building, 6752 Ayala Avenue corner Makati Avenue, Makati City, Philippines, 1228', 'inquires@anchorland.com.ph', '+632 886 3572 to 74;');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (21, 'Anglo Philippine Holdings Corporation', '6th Floor Quad alpha Centrum, 125 Pioneer St. Mandaluyong City', 'aphc1996@yahoo.com', '(632) 6315139');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (22, 'Apex Mining Co., Inc.', 'Unit 3304-B West Tower, PSE Centre, Exchange Road, Ortigas Center, Pasig City, Philippines 1605', null, '706-2805');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (23, 'Apollo Global Capital, Inc.', 'Unit 1801 East tower, Philippine Stock Exchange Center, Exchange Road, Ortigas Center, Pasig City', null, '(632) 910-6429');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (24, 'Araneta Properties, Inc.', '21/F Citibank Tower, Paseo de Roxas cor. Valero St., Salcedo Village, Makati City', ' ara@info.com.ph', '848-1501 to 04');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (25, 'Arthaland Corporation', '8/F Picadilly Star Building, 4th Avenue corner 27th Street, Bonifacio Global City, Taguig City, Philippines', 'spverano@arthaland.com', '403-6910');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (26, 'Asia Amalgamated Holdings Corporation', 'Uniwide, 1695 Rizal Ave., Ext., Grace Park, Caloocan city', 'belindabatuegas@yahoo.com', '363-7811 ');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (27, 'Asia United Bank Corporation', 'Joy Nostalg Center No. 17, ADB Avenue, Ortigas Center, Pasig City, Philippines', 'arnaldomac@aub.com.ph', '(632) 633-6888 ');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (28, 'Asiabest Group International Inc.', '22nd Floor The Peak Tower, 107 LP Leviste St., Salcedo Village, Makati City', 'legal@rsbernaldo.com', '
920-9306');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (29, 'Asian Terminals, Inc.', 'ATI Head Office: A. Bonifacio Drive, Port Area, Manila', 'mreyes@asianterminals.com.ph', '528-6000');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (30, 'Atlas Consolidated Mining and Development Corporation', '503-P Pacific Tower,
5F Five E-Com Center,
Palm Coast Ave. corner Pacific Drive,
Mall of Asia Complex, Pasay City', ' acmdcmla@info.com.ph', '(632) 584 9788');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (31, 'Atok-Big Wedge Co., Inc.', '10th Floor, Alphaland Southgate Tower, 2258 Chino Roces Avenue corner EDSA, Makati City', 'gherrera@aranetagroup.com', '3046282.0');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (32, 'Ayala Corporation', '34/F, Tower One and Exchange Plaza, Ayala Triangle, Ayala Avenue, Makati City', 'acquery@ayala.com.ph', '908-3000');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (33, 'Ayala Land, Inc.', '31/F, Tower One and Exchange Plaza, Ayala Triangle, Ayala Avenue, Makati City', ' iru@ayalaland.com.ph', '908-3000');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (34, 'BDO Leasing and Finance, Inc.', 'BDO Leasing Centre, Corinthian Gardens, Ortigas Avenue, Quezon City', 'reyes.luis@bdo.com.ph', '635-6416');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (35, 'BDO Unibank, Inc.', 'BDO Corporate Center, 7899 Makati Avenue, Makati City', 'hrmd@bdo.com.ph', '40-7000');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (36, 'BHI Holdings, Inc.', '22/F The Pearlbank Center, 146 Valero St., Salcedo Village, Makati City 1227', 'bhiholdings@broadbandphilippines.net', '817-14-06');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (37, 'Bank of the Philippine Islands', 'BPI Building, 6768 Ayala Ave. cor. Paseo de Roxas, Makati City 1200', 'expressonline@bpi.com.ph', '816-9705');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (38, 'Basic Energy Corporation', '7/F Basic Petroleum Building, 104 Carlos Palanca, Jr. St., Legaspi Village, Makati City 1229', 'basic@basicenergy.ph', '817-8596 to 98');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (39, 'Belle Corporation', '5th Flr., Tower A., Two E-Com Center, Palm Coast Avenue, Mall of Asia Complex, Pasay City, Metro Manila, Philippines', ' info@bellecorp.com', '
(+632) 662-8888');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (40, 'Benguet Corporation', '7/F, Universal-Re Building, 106 Paseo de Roxas, Makati City 1226', ' admin@benguetcorp.com', '(632) 812-1380');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (41, 'Berjaya Philippines Inc.', '9/F Rufino Pacific Tower, 6784 Ayala Ave corner Herrera Street, Makati City, Metro Manila', 'blaw@attglobal.net', '811-0668');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (42, 'Bloomberry Resorts Corporation', '
Solaire Executive Offices, Solaire Resort and Casino, Asean Ave., Entertainment City, Paranaque City', 'lvenezuela@bloomberry.ph', '(632) 883-8920 ');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (43, 'Bogo-Medellin Milling Company, Inc.', 'Barangay Luy-a, Medellin, Cebu City', 'tontonbaluyot@gmail.com', '(032) 436-2178');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (44, 'Boulevard Holdings, Inc.', 'Unit 1704, 17/F The Peak Tower, 107 L. P. Leviste St., Salcedo Village, Makati City', 'maurobadiola@yahoo.com', '753-1405');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (45, 'Bright Kindle Resources & Investments Inc.', '16th Floor Citibank Tower, 8741 Paseo de Roxas, Makati City', 'service@brightkindle.com', '833-0769');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (46, 'COL Financial Group, Inc.', 'Unit 2401B East Tower, PSE Centre, Exchange Road, Ortigas Center, Pasig City', 'helpdesk@citiseconline.com', '636 5411 - 30');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (47, 'Calata Corporation', 'Level 16 Tower 2, The Enterprise Center Ayala Avenue Cor Paseo de Roxas Makati City Philippines 1226', 'info@calatacorp.com', '(+632) 511-1701');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (48, 'Cebu Air, Inc.', 'Cebu Pacific Building, Domestic Road, Barangay 191, Zone 20, Pasay City', null, '(632) 802-7000');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (49, 'Cebu Holdings, Incorporated', '20th Floor, Ayala Center Cebu Tower, Bohol Street, Cebu Business Park, Cebu City', 'alicaya.noel@cebuholdings.com', '(032) 888-3700');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (50, 'Cebu Landmasters, Inc.', '10th Floor, Park Centrale Tower, Cebu I.T. Park, J.M. Del Mar Street, Lahug, Cebu City', 'stephen@cebulandmasters.com', '+63 32 401-1120');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (51, 'Cebu Property Ventures and Development Corporation', '20th Floor, Ayala Center Cebu Tower, Bohol Street, Cebu Business Park, Cebu City', 'alicaya.noel@cebuholdings.com', '(032) 888-3700');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (52, 'Cemex Holdings Philippines, Inc.', '34th Floor Petron Mega Plaza Building, 358 Sen. Gil J. Puyat Avenue, Makati City', 'paulvincent.arcenas@cemex.com', '
(632) 849 3600');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (53, 'Central Azucarera de Tarlac, Inc.', 'First Lucky Place, 2259 Pasong Tamo Extension, Makati City', '
jcsolegal@yahoo.com', '(632) 818-6270');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (54, 'Centro Escolar University', 'No. 9 Mendiola Street, San Miguel, Manila', 'asregalado@ceu.edu.ph', '
735-2513');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (55, 'Century Pacific Food, Inc.', '7th Floor, Centerpoint Building, Julia Vargas Avenue corner Garnet Street Ortigas Center, 1605 Pasig City', 'investorrelations@centurypacific.com.ph', '(632) 633 8855');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (56, 'Century Peak Metals Holdings Corporation', '
1403 & 1404 Equitable Bank Tower Bldg., 8751 Paseo de Roxas, Makati City', 'dan_antonio@yahoo.com ', '(632) 856-0999');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (57, 'Century Properties Group, Inc.', '21st Floor, Pacific Star Building, Sen. Gil Puyat Avenue corner Makati Avenue Makati City', 'webmaster@century-properties.com', '7935541.0');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (58, 'Chelsea Logistics Holdings Corp.', 'Stella Hizon Reyes Road, Bo. Pampanga, Davao City 8000, Philippines', 'eunika.maloles@chelseashipping.ph', '
+63 82 224 5373');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (59, 'Chemical Industries of the Philippines, Inc.', 'Chemphil Building, 851 Antonio S. Arnaiz Ave., Legaspi Village, Makati City 1229', ' chemphilgroup@chemphil.com.ph', '818-8711 to 28');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (60, 'China Banking Corporation', '8745 China Bank Building, Paseo de Roxas cor. Villar St., Makati City 1226 P.O. 2182', 'investor-relations@chinabank.ph', '885-5555');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (61, 'Cirtek Holdings Philippines Corporation', '116 East Main Avenue Phase V-SEZ, Laguna Technopark, Biñan, Laguna', 'as.buyawe@cirtek.ph', '
(632) 7296206');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (62, 'City & Land Developers, Incorporated', '2F Cityland 10 Tower 1, 156 H.V. Dela Costa St. Makati City', 'cldi_rb@cityland.net', '
893-60-60');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (63, 'Cityland Development Corporation', '2F Cityland 10 Tower 1, 156 H.V. Dela Costa St. Makati City', 'cdc_rb@cityland.net', '
893-60-60');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (64, 'Citystate Savings Bank, Inc.', '2F Citystate Centre Bldg., 709 Shaw Blvd., Pasig City', 'info@psbank.com.ph', '(632) 470-3333');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (65, 'Coal Asia Holdings Incorporated', '3rd floor JTKC Center, 2155 Don Chino Roces Ave., Makati City ', 'rosanna.desiderio@titanmining.com ', '818-6772');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (66, 'Concepcion Industrial Corporation', '308 Sen. Gil Puyat Ave., Makati City, Metro Manila, Philippines', 'investorrelations@cic.ph', '(632) 772-1819');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (67, 'Concrete Aggregates Corporation', '9th Floor, Ortigas Building, Ortigas Avenue, Pasig City', 'info@concreteaggregatescorp.com', '631-1231');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (68, 'Cosco Capital, Inc.', 'No. 900 Romualdez St., Paco, Manila', 'coscocapitalinc@gmail.com', '522-8801 loc. 125');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (69, 'Crown Asia Chemicals Corporation', 'Km. 33 MacArthur Highway, Bo. Tuktukan, Guiguinto, Bulacan', 'tpvillanueva@crownpvc.com.ph', '(+632) 413-8032 to 33');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (70, 'Crown Equities, Inc.', 'Crown Center, 158 Jupiter cor. N. Garcia Sts., Bel-Air, Makati City 1209', 'cei@crownequitiesinc.com', '(632) 899-0081');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (71, 'Cyber Bay Corporation', 'Suite 2402, Discovery Center, 25 ADB Avenue, Ortigas Center, Pasig City', 'psuchianco@cyber-bay.com', '(632) ) 636-6080');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (72, 'D&L Industries, Inc.', '65 Calle Industria, Bagumbayan, Quezon City', '
info@dnl.com.ph', '
+63(2) 635-0680');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (73, 'DFNN, Inc.', '3F Bonifacio Technology Center, 31st St. cor. 2nd Ave., Bonifacio Global City, Taguig', 'patty@dfnn.com', '
818-0973 / 75 / 78-79');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (74, 'DMCI Holdings, Inc.', '3rd Floor Dacon Bldg. 2281 Don Chino Roces Avenue, Makati City', '
investor_inquiries@dmcinet.com', '(632) 888-3000');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (75, 'Da Vinci Capital Holdings, Inc.', 'Barrio San Antonio, Sto. Tomas, Batangas', 'hotline@mariwasa.com', '(043) 778-2935 ');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (76, 'Del Monte Pacific Limited', 'Craigmuir Chambers, PO Box 71 Road Town, Tortola, the British Virgin Islands', 'jluy@delmontepacific.com', '+65 6594 0980');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (77, 'Discovery World Corporation', 'Principal Office: Station 1, Balabag, Malay, Aklan; Corporate Office: 2F JTKC Centre 2155 Chino Roces Ave., Makati City', 'jean.codinera@discovery.com.ph', '(+632) 813-8857');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (78, 'Dizon Copper-Silver Mines, Inc.', '7th Floor, Peaksun Bldg.
1505 Princeton Street
Brgy. Wack-Wack Greenhills East
Mandaluyong City, Philippines', 'dizon_kalahi@yahoo.com', '721-3961');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (79, 'DoubleDragon Properties Corp.', '16th Floor, 6750 Building, Ayala Avenue, Makati City, Philippines 1226 (Corporate Office)', 'investors@doubledragon.com.ph', '(+632) 856-7111');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (80, 'EEI Corporation', 'No. 12 Manggahan Street, Bagumbayan, Quezon City', 'grthipolito@eei.com.ph', '635-0843 up to 56');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (81, 'Eagle Cement Corporation', 'No. 153 EDSA, Barangay Wack-Wack, Mandaluyong City, Metro Manila, Philippines', '
ir@eagle-cement.com.ph', '
(02) 301-3453');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (82, 'East West Banking Corporation', 'Podium of The Beaufort, 5th Avenue corner 23rd Street, Fort Bonifacio Global City, Taguig City ', 'service@eastwestbanker.com', '(632)870-3500');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (83, 'EasyCall Communications Philippines, Inc.', '2/F, Mary Bachrach Building, 25th cor. A.C. Delgado Streets, Port Area, Manila', 'eta@easycall.com.ph', '+632 754 8688');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (84, 'Emperador Inc.', '7th Floor, 1880 Eastwood Avenue, Eastwood City CyberPark, 188 E. Rodriguez Jr. Avenue, Bagumbayan, Quezon City', 'empmarketing@emperadordistillers.com', '
(632) 7092038 to 40');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (85, 'Empire East Land Holdings, Inc.', '21st Floor, The World Centre, 330 Sen. Gil Puyat Ave., Makati City', 'jquiazon@megaworldcorp.com', '867-8048');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (86, 'Energy Development Corporation', '38th Floor One Corporate Center, Julia Vargas Avenue, Ortigas Center, Pasig City', 'applicant@energy.com.ph', '667-7332');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (87, 'Euro-Med Laboratories Phil., Inc.', 'PPL Building, 1000-1046 United Nations Avenue, Manila', 'corporate@euromedlab.net', '5240091-98');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (88, 'Ever-Gotesco Resources and Holdings, Inc.', '12/F, Ever Gotesco Corporate Center, 1958 C. M. Recto Ave., Manila', null, '735-6901 to 08');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (89, 'Export and Industry Bank, Inc.', 'Export Bank Plaza, Chino Roces cor. Sen. Gil J. Puyat Aves., Makati City 1200', 'rvmaala@exportbank.com.ph', '
878-0000');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (90, 'F & J Prince Holdings Corporation', '
5th Floor, Citibank Center, 8741 Paseo de Roxas, Makati City', ' prinznet@compass.com.ph', '8927133.0');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (91, 'Far Eastern University, Incorporated', 'Nicanor Reyes Sr. St., Sampaloc, Manila', 'webmaster@feu.edu.ph', '735-5621');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (92, 'Filinvest Development Corporation', '6F, The Beaufort, 5th Ave. Corner 23rd Street, Bonifacio Global City, Taguig City', 'ir@filinvestgroup.com', '(632) 918-8188');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (93, 'Filinvest Land, Inc.', '79 Edsa, Brgy. Highway Hills, Mandaluyong City', 'ir@filinvestland.com', '7270431.0');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (94, 'Filipino Fund, Inc.', '17/F BPI HO Building, Ayala Ave., cor. Paseo de Roxas, Makati City 1200', 'dcmauhay@bpi.com.ph', '845-5041 / 5070 to 71');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (95, 'Filsyn Corporation', 'Unit 8, 5B Pearlbank Centre, 146 Valero Street, Salcedo Village, Makati City', 'info@filsyncorp.com', '815-9320');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (96, 'First Abacus Financial Holdings Corporation', '2904-A East Tower, PSE Centre, Exchange Road Ortigas Center, Pasig City', 'customerservice@abacus-sec.com', '625-7986');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (97, 'First Gen Corporation', '6F Rockwell Business Center, Tower 3, Ortigas Avenue, Pasig City, 1604', 'rrhernandez@firstgen.com.ph ', '449-6400');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (98, 'First Metro Philippine Equity Exchange Traded Fund, Inc.', '18th Floor, PS Bank Center, Paseo de Roxas corner Sedeno St., 1227 Makati City, Philippines', null, '(632) 891-2860');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (99, 'First Philippine Holdings Corporation', '6th Floor Rockwell Business Center Tower 3 Ortigas Avenue, Pasig City 1604', 'InvRel@fphc.com', '2-6318024');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (100, 'Forum Pacific, Inc.', '35/F One Corporate Center , Doña Julia Vargas Avenue, Corner Meralco Avenue, Pasig City, Metro Manila', ' feiexplo@mozcom.com', '706-7888');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (101, 'GEOGRACE Resources Philippines, Inc.', '7th Floor, Peaksun Building, 1505 Princeton Street, corner Shaw Blvd., Brgy. Wack-Wack, Greenhills East, Mandaluyong City ', 'info@geograce.com', '570-9754');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (102, 'GMA Holdings, Inc.', 'GMA Network Center, GMA Complex EDSA Diliman Quezon City', 'investor_relations@gmanetwork.com', '(632) 982-7777');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (103, 'GMA Network, Inc.', 'GMA Network Center, GMA Complex EDSA Diliman Quezon City', null, '(632) 982-7777');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (104, 'GT Capital Holdings, Inc.', '43/F GT Tower International, Ayala Avenue corner H.V. Dela Costa Street, Makati City 1227', 'gtcap@gtcapital.com.ph', '(632) 836 4500');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (105, 'Ginebra San Miguel, Inc.', '3rd and 6th Floors, San Miguel Properties Centre, St. Francis Street, Ortigas Center, Mandaluyong City, Philippines', 'ginebrasanmiguel@smg.sanmiguel.com.ph', '841-5100');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (106, 'Global Ferronickel Holdings, Inc.', '7F Corporate Business Center, 151 Paseo de Roxas corner Arnaiz Street, Makati City', 'info@gfni.com.ph', '(632) 5197888');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (107, 'Global-Estate Resorts, Inc.', '16th Floor, Alliance Global Tower, 36th Street corner 11th Avenue, Uptown Bonifacio, Taguig City, 1634, Metro Manila', 'legal@global-estate.ph', '328-4370 to 78');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (108, 'Globalport 900, Inc.', 'Unit 2701, One Corporate Centre, Meralco Avenue corner Julia Vargas Avenue, Ortigas Center, Pasig City', 'jbr@mapcentral.ph', '637-8851');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (109, 'Globe Telecom, Inc.', 'The Globe Tower, 32nd Street corner 7th Avenue, Bonifacio Global City, Taguig', 'ir@globetel.com.ph', '730-2000');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (110, 'Golden Haven Memorial Park, Inc.', 'San Ezekiel, C5 Extension, Las Piñas City', 'ir@goldenhaven.com.ph', '+63(2) 873-2922/');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (111, 'Grand Plaza Hotel Corporation', '10/F The Heritage Hotel Manila, Roxas Boulevard cor. EDSA Extension, Pasay City', ' inquire@heritagehotelmanila.com', '854-8838');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (112, 'Greenergy Holdings Incorporated', 'Unit 112 Cedar Mansions II, #7 Escriva Drive, Ortigas Center, Barangay San Antonio, Pasig City', 'greenergy@ghi.com.ph', '(02) 997-5184');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (113, 'Harbor Star Shipping Services, Inc.', '2224 Gen. A Bonifacio Street corner South Superhighway, Bangkal, Makati City 1233, Metro Manila', 'info@harborstar.com.ph', ' (+632) 889-6410');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (114, 'Holcim Philippines, Inc.', '7th Floor Two World Square, McKinley Hill, Fort Bonifacio, Taguig City 1634', 'allen.arbis@holcim.com.ph', '459-3333');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (115, 'House of Investments, Inc.', '3/F Grepalife Building, 219 Sen. Gil J. Puyat Ave., Makati City 1200', ' investment@hoi.com.ph', '815-9636 to 38');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (116, 'I-Remit, Inc.', '26/F Discovery Centre, ADB Avenue, Ortigas Centre, Pasig City, Philippines', 'investor_relations@iremit-inc.com', '(02) 706-9999');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (117, 'IP E-Game Ventures, Inc.', '1003, 10th Floor, Centerpoint Condominium, Garnet Road corner Julia Vargas Avenue, Ortigas Center, Pasig City, Metro Manila, Phi', null, null);
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (118, 'IPM Holdings, Inc.', 'Unit 103, Ground Floor, Prestige Tower Condominium, F. Ortigas Jr. Avenue Ortigas Center, Pasig City ', 'info@ipmholdings.com.ph', '(632)8975257');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (119, 'IRC Properties, Inc.', '35/F Rufino Pacific Tower, 6784 Ayala Avenue, Makati City 1223', 'admin@interportresources.com', '750-2000');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (120, 'ISM Communications Corporation', '3F Alegria Alta Building, Don Chino Roces Ave. Ext, Makati City ', 'jdslarrazabal@ismcorp.com.ph', '02-310-1916');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (121, 'Imperial Resources, Inc.', 'Unit 202 Villa Building, No. 78 Jupiter Street corner Makati Avenue, Barangay Bel-Air, Makati City', ' vraimp@impactnet.com', '632-7242986');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (122, 'Integrated Micro-Electronics, Inc.', 'Principal office: 34/F, Tower One, Ayala Triangle, Ayala Avenue, Makati City / North Science Avenue, Laguna Technopark SEPZ, Biñ', 'corporatesecretary@global-imi.com', '756-6940 loc. 5300');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (123, 'International Container Terminal Services, Inc.', '3/F ICTSI Administration Building, MICT South Access Road, Manila 1012', ' info@ictsi.com', '245-4101');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (124, 'Ionics, Inc.', 'Light Industry & Science Park, Cabuyao, Laguna', 'rose.vicente@ionics-ems.com', '5844615 to 16');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (125, 'Island Information & Technology, Inc.', '4/F 4-B Vernida I Condominium, 120 Amorsolo St., Legaspi Village, Makati City', 'islandinfotech@yahoo.com', '813-2839');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (126, 'Italpinas Development Corporation', 'Unit 9A, 9/F Country Space 1 Building, 133 H.V. Dela Costa St., Salcedo Village, Makati City 1200', 'investors@italpinas.com', '(02) 893-0328;');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (127, 'JG Summit Holdings, Inc.', '43/F Robinsons Equitable Tower, ADB Avenue corner Poveda St., Ortigas Center, Pasig City', 'bjsebastian@jgsummit.com.ph', '633-7631 to 40');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (128, 'Jackstones, Inc.', '593 Antonio Drive, Bagumbayan, Taguig City, Philippines 1630', 'anthonyperalta@cochingyanperalta.com', '687-0808');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (129, 'Jollibee Foods Corporation', '10/F Jollibee Plaza Building, Emerald Ave., Ortigas Center, Pasig City 1600', 'president@jollibee.com.ph', '634-1111');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (130, 'Jolliville Holdings Corporation', '4/F 20 Lansbergh PlaceTomas Morato Ave. cor. Scout Castor St. Quezon City 1103', ' info@jhc.com', '373-3038');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (131, 'Keppel Philippines Holdings, Inc.', 'Unit 3-B Country Space 1 Building, 133 Sen. Gil Puyat Avenue, Salcedo Village, Brgy. Bel Air, Makati City', 'kph_mac@info.com.ph', '892-1816');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (132, 'Keppel Philippines Properties, Inc.', 'Units 2203-2204 Raffles Corporate Center, F. Ortigas Jr. Road, Ortigas Center, Pasig City', ' keppel.prop@kepland.com.ph', '584-6170');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (133, 'LBC Express Holdings, Inc.', 'LBC Hangar, General Aviation Centre, Domestic Airport Road, Pasay City', 'lbcholdings@lbcexpress.com', '(+632) 856-8510');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (134, 'LMG Chemicals Corporation', 'Chemphil Building, 851 Antonio Arnaiz Ave., Makati City', 'chemphilgroup@.chemphil.com.ph', '818-8711 to 26');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (135, 'LT Group, Inc.', '11/F Unit 3 Bench Tower 30th Street corner Rizal Drive, Crescent Park West 5, Bonifacio Global City, Taguig City ', 'info@ltg.com.ph', '808-1266');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (136, 'Leisure & Resorts World Corporation', '26/F West Tower, PSE Centre, Exchange Road, Ortigas Center, Pasig City', ' lrwc@philcom.com.ph', '886-0133');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (137, 'Lepanto Consolidated Mining Company', '21/F Lepanto Building, 8747 Paseo de Roxas, 1226 Makati City', ' mis@lepantomining.com', '815-9447');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (138, 'Liberty Flour Mills, Inc.', 'Liberty Building, 835 Antonio Arnaiz Ave., Makati City 1200', ' libertyflour@pacific.net.ph', '892-5011 to 29');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (139, 'Lodestar Investment Holdings Corporation', '7th Floor Peaksun Bldg., 1505 Princeton St., corner Shaw Blvd., Brgy. Wack Wack Greenhills East, Mandaluyong City ', null, '920-9306');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (140, 'Lopez Holdings Corporation', '4/F Benpres Building, Exchange Road cor. Meralco Ave., Ortigas Center, Pasig City', 'InvestorRelations@lopez-holdings.ph', '449-2345');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (141, 'Lorenzo Shipping Corporation', '20th Floor, Times Plaza Bldg., United Nations Avenue, Ermita, Manila', 'rjdelrosario@lorenzoshipping.com', '245-7481 to 88');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (142, 'MEDCO Holdings, Inc.', '31/F Rufino Pacific Tower, 6784 Ayala Ave., Makati City 1229', 'maic@medco.com.ph', '811-0465 to 66');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (143, 'MJC Investments Corporation', '12/F Strata 100 Building, Emerald Avenue, Ortigas Center, Pasig City 1605', null, '(02) 632-7373');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (144, 'MRC Allied, Inc.', '5th Floor, Eurovilla 4 Building, No. 853 Arnaiz Ave., Makati City', ' mrc_allied@yahoo.com', '846-7910');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (145, 'Mabuhay Holdings Corporation', '35th Floor, Rufino Pacfic Tower, 6784 Ayala Avenue, Makati City 1223', 'admin@mabuhayholdingscorp.com', '(632) 750-2000');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (146, 'Mabuhay Vinyl Corporation', '3/F Philamlife Salcedo Centre, 126 L. P. Leviste St., Salcedo Village, Makati City', 'filvinyl@mvc.com.ph', '817-8971 to 76');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (147, 'Macay Holdings, Inc.', '137 Yakal Street, San Antonio Village, Makati City 1203', 'investor.relations@macayholdings.com.ph', '893-0733 ');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (148, 'MacroAsia Corporation', '12th Floor, PNB Allied Bank Centre, 6754 Ayala Avenue, Makati City 1226', 'info@macroasiacorp.com', '(+632) 840 2001');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (149, 'Makati Finance Corporation', '3/F, Mazda Makati Building, 2301 Chino Roces Avenue, Brgy. Magallanes, Makati City 1231', null, '(0632) 751-8132');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (150, 'Manila Broadcasting Company', 'MBC Building, Star City, CCP Complex, Roxas Boulevard, Pasay City', ' jpmacuja@mbcradio.net', '832-6149');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (151, 'Manila Bulletin Publishing Corporation', 'Manila Bulletin Building, Muralla corner Recoletos Sts., Intramuros, Manila', ' purchase@mb.com.ph', '527-8121');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (152, 'Manila Electric Company', 'Lopez Building, Ortigas Avenue, Pasig City 0300', ' corcom@meralco.com.ph', '631-5567');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (153, 'Manila Jockey Club, Inc.', '14th Floor Strata 100 Building , F. Ortigas Jr. Road, Ortigas Center, Pasig City 1605', 'mjci@mindgate.net', '(02) 687-9889');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (154, 'Manila Mining Corporation', '20/F Lepanto Building, 8747 Paseo de Roxas, Makati City', ' odette.javier@lepantomining.com', '815-9447 to 50');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (155, 'Manila Water Company, Inc.', '2/F MWSS Administration Building, 489 Katipunan Road, Balara, Quezon City 1105', ' info@manilawater.com', '(632) 981-8129');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (156, 'Manulife Financial Corporation', 'Manulife Centre, LKG Tower, 6801 Ayala Ave., , Makati City', ' investor_relations@manulife.com', '884-5433');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (157, 'Marcventures Holdings, Inc.', '4F, Citibank Center, Paseo de Roxas, Makati City', 'mhicorporate@marcventures.com.ph ', '831-4479');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (158, 'Max''s Group, Inc.', '11th Floor EcoPlaza Building, 2305 Chino Roces Avenue Extension Makati City 1231', 'info@maxsgroupinc.com', '7849000.0');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (159, 'Megawide Construction Corporation', '2/F Spring Building, Arnaiz Avenue corner P. Burgos Street, Pasay City, Metro Manila', 'marketing@megawide.com.ph', '376-3425');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (160, 'Megaworld Corporation', '30th Floor, Alliance Global Tower, 36th Street cor. 11th Avenue, Uptown Bonifacio, Taguig City 1634, Metro Manila, Philippines', 'jquiazon@megaworldcorp.com', '8946431.0');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (161, 'Melco Resorts and Entertainment (Philippines) Corporation', 'Asean Avenue cor. Roxas Boulevard, Brgy. Tambo, Parañaque City 1701', 'mrp_ir@melco-resorts.com', '(02) 691-8899');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (162, 'Metro Alliance Holdings & Equities Corp.', '35th Floor Unit 3501-3502 One Corporate Centre, Dona Julia Vargas Ave., cor. Meralco Ave., Ortigas Centre, Pasig City', 'info@wellex.com.ph', '706-7888');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (163, 'Metro Global Holdings Corporation', '7/F Renaissance Tower, Meralco Avenue, Pasig City 1600', 'jojo_bondoc@yahoo.com', '633-6205');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (164, 'Metro Pacific Investments Corporation', '10th Floor, MGO Buiding; De La Rosa corner Legazpi Streets, Legazpi Village, Makati City, Philippines', 'metro@metropacific.com', '888-0888');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (165, 'Metro Retail Stores Group, Inc.', 'Vicsal Building, corner of C.D. Seno and W.O. Seno Streets Guizo, North Reclamation Area, Mandaue City', 'investor.relations@metrogaisano.com', '
(6332) 236-8390');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (166, 'Metropolitan Bank & Trust Company', 'Metrobank Plaza, Sen. Gil J. Puyat Ave., Makati City 1200', ' avviray@metrobank.com.ph', '898-8000 ');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (167, 'Millennium Global Holdings, Inc.', 'Blk 1 Lot 1, Dahlia St. corner J.P. Rizal St., Sto. Nino, Paranaque City', 'info@millennium.globalholdingsinc.com', '+632 5512575 ');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (168, 'National Reinsurance Corporation of the Philippines', '31st Floor, BPI-Philam Life Makati, 6811 Ayala Avenue, Makati City, Philippines.', 'reyes.al@nrcp.com.ph ', '988-7400');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (169, 'NextGenesis Corporation', '3/F Asiatrust Bank Building, 1424 Quezon Ave., Quezon City 1100', 'dcong@asiatrustbank.com', '(632) 924-5787');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (170, 'NiHAO Mineral Resources International, Inc.', '7th Floor, Peaksun Building, 1505 Princeton Street, corner Shaw Blvd., Brgy. Wack-Wack, Greenhills East, Mandaluyong City ', 'info@nihaometals.com', '570-9754');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (171, 'Nickel Asia Corporation', '28th Floor, NAC Tower, 32nd Street, Bonifacio Global City, Taguig City, Metro Manila 1634', null, '(632) 798-7622');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (172, 'Now Corporation', 'Unit 5-I, 5th Floor, OPL Building, 100 C. Palanca Street corner Dela Rosa and Gil Streets, Legaspi Village, Makati City', 'info@now-corp.com', '7500211.0');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (173, 'Omico Corporation', 'Unit 401 Capri Oasis-Solare Bldg., Dr. Sixto Antonio Ave., Maybunga, Pasig City', ' omico@i-manila.com.ph', '(632) 637-6923 to 25');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (174, 'Oriental Peninsula Resources Group, Inc.', '81 Sen. Gil Puyat Ave. Palanan, Makati City, Philippines', 'inquire@orientalpeninsula.com', '+632 8891129');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (175, 'Oriental Petroleum and Minerals Corporation', '40/F c/o JG Summit, Robinson`s Equitable Tower, ADB Ave., Ortigas Center, Pasig City 1600', ' orientalpetroleum@digitelone.com', '633-7631 loc. 278 / 281');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (176, 'PAL Holdings, Inc.', '8th Floor, PNB Financial Center, President Diosdado Macapagal Avenue, CCP Complex, Pasay City', 'corpcomms@pal.com.ph', '(02) 816-3451');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (177, 'PHINMA Energy Corporation', '11th Floor, Phinma Plaza, 39 Plaza Drive, Rockwell Center, Makati City', 'avr@trans-asia.phinma.com', '(632) 870-0100');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (178, 'PICOP Resources, Inc.', '2/F Moredel Building 2280 Pasong Tamo Extension, Makati City', ' srmo@i-next.net', '813-2081/5308/5309/5310');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (179, 'PLDT Inc.', 'Ramon Cojuangco Building, Makati Avenue, Makati City', 'Pldt_ir_center@pldt.com.ph', '816-8553');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (180, 'PTFC Redevelopment Corporation', '802 A. Bonifacio St. Balintawak, Quezon City', null, '362-1808');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (181, 'PXP Energy Corporation', '2/F, LaunchPad Reliance corner Sheridan Streets, Mandaluyong City', 'admin@pxpenergy.com.ph', '(632) 631-1381 to 88');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (182, 'Pacific Online Systems Corporation', '28th Floor East Tower, Philippine Stock Exchange Centre, Exchange Road, Ortigas Center, Pasig City', 'contactus@pacificonline.com.ph', '(632) 636-5281');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (183, 'Pacifica, Inc.', 'Manila Harbour Centre, R-10, Vitas, Tondo, Manila, Philippines 1013', 'mlcarilla@yahoo.com', '516-7888');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (184, 'Panasonic Manufacturing Philippines Corporation', 'Bo. Mapandan, Ortigas Ave. Extn., Taytay, Rizal', 'pmpc_op@ph.panasonic.com', '818-7739');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (185, 'Paxys, Inc.', '15th Floor, 6750 Ayala Office Tower, Ayala Avenue, Makati City 1226', ' paxys@acspacific.com', '(+632) 250-3800');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (186, 'Pepsi-Cola Products Philippines, Inc.', 'Km. 29 National Road Tunasan Muntinlupa City Philippines 1773', 'partho.chakrabarti@pcppi.com.ph', '(02) 865-6297');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (187, 'PetroEnergy Resources Corporation', '7/F JMT Condominium Bldg. ADB Ave., Ortigas Center, Pasig City', ' petro-energy@petroenergy.com.ph', '637-2917');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (188, 'Petron Corporation', 'SMC Head Office Complex, 40 San Miguel Avenue, 1550 Mandaluyong City', 'contactus@petron.com', '886-3888');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (189, 'PhilWeb Corporation', '6/F Adamson Centre, 121 L.P. Leviste Street, Salcedo Village, Makati City, Philippines', 'info@philweb.com.ph', '2365577.0');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (190, 'Philab Holdings Corp.', '8th Floor, 1128 38th Avenue, Fort Bonifacio Global City, Taguig City, Metro Manila', 'info@philab.com', '(02)5519639');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (191, 'Philcomsat Holdings Corporation', '12/F Telecoms Plaza Building, 316 Sen. Gil Puyat Avenue, Makati City', 'phc@philcomsatgroup.com.ph', '(02) 815-8406');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (192, 'Philex Mining Corporation', '2/F, LaunchPad Reliance corner Sheridan Streets, Mandaluyong City', ' philex@info.com.ph', '631-1381 to 88');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (193, 'Philippine Bank of Communications', 'PBCom Tower, 6785 Ayala Avenue corner V.A. Rufino Street, Makati City', ' info@pbcom.com.ph', '830-7062');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (194, 'Philippine Business Bank', '350 Rizal Avenue Extension corner 8th Avenue, Grace Park, Caloocan City', 'info@pbb.com.ph', '(632) 363-3333');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (195, 'Philippine Estates Corporation', 'Units 3503 & 3504, 35th Floor One Corporate Center, Vargas cor Merlaco Ave., Ortigas Center, Pasig City', ' phes@edsamail.com.ph', '687-5660 to 70');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (196, 'Philippine H2O Ventures Corp.', '4th floor Lansbergh Place Bldg., 170 Tomas Morato Ave, Quezon City, Philipines', 'info@h2o.ph', '+632-373-3038');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (197, 'Philippine National Bank', 'PNB Financial Center, President Diosdado Macapagal Boulevard, Pasay City 1300', 'customercare@pnb.com.ph', '891-6040 to 70');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (198, 'Philippine National Construction Corporation', 'PNCC Building, Km.15 East, Service Road, Bicutan, Paranaque City', 'pncc@pncc.ph', '8460209.0');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (199, 'Philippine Racing Club, Inc.', 'Saddle and Clubs Leisure Park, Brgy. Sabang, Naic, Cavite', ' sta-ana-park@pacific.com.ph', '890-4015');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (200, 'Philippine Realty and Holdings Corporation', 'Main Office Address: Andrea North Complex, Balete Drive corner N. Domingo St., New Manila , Quezon City / Satellite Office Addre', 'info@philrealty.com.ph', '631-3179, 636-1170');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (201, 'Philippine Savings Bank', 'PSBank Tower, 777 Paseo de Roxas Cor. Sedeño St. , Makati City', 'info@psbank.com.ph', '845-8888');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (202, 'Philippine Seven Corporation', '7/F The Columbia Tower Ortigas Ave., Mandaluyong City', 'psc-corp@7-eleven.com.ph ', '(02) 724-4441 to 51');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (203, 'Philippine Telegraph and Telephone Corporation', '6/F Spirit of Communication Center106 Carlos Palanca Jr. St. Legaspi Village, Makati City', 'crm@ptt.com.ph', '815-9961');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (204, 'Philippine Trust Company', 'Philtrust Bank Building 1000 United Nations Ave. Corner San Marcelino St., Manila', ' ptc@bancnet.net', '524-9061');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (205, 'Phinma Corporation', 'Level 12, Phinma Plaza, 39 Plaza Drive Rockwell Center, Makati City 1200', 'ciobci@phinma.com.ph', '870-0100');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (206, 'Phinma Petroleum and Geothermal, Inc.', '11th Floor, The PHINMA Plaza, 39 Plaza Drive Rockwell Center, Makati City 1210', 'grkatigbak@phinma.com.ph', '(632) 870 0130');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (207, 'Phoenix Petroleum Philippines, Inc.', 'Stella Hizon Reyes Road, Bo. Pampanga, Davao City, Philippines', 'info@phoenixfuels.ph', '(082)235 8888');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (208, 'Pilipinas Shell Petroleum Corporation', 'Shell House, No. 156 Valero Street, Salcedo Village, Brgy. Bel-Air, Makati City 1227', 'generalpublicenquiries-ph@shell.com', '(632) 816-6501');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (209, 'Premiere Horizon Alliance Corporation', 'Unit 1705, 17th Floor, East Tower, Philippine Stock Exchange Center, Ortigas Center, Pasig City', 'investors@premierehorizon.com', '632) 632-7714');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (210, 'Premium Leisure Corp.', '5th Floor, Tower A, Two E-Com Center, Palm Coast Avenue, Mall of Asia Complex, Pasay City', 'manuel.gana@bellecorp.com', '(+632) 662-8888');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (211, 'Prime Media Holdings, Inc.', '16th Floor, Citibank Tower, 8741 Paseo de Roxas, Makati City', 'service@primemediaholdingsinc.com', '831-4479 loc. 403');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (212, 'Prime Orion Philippines, Inc.', 'Unit 1014 Tower One and Exchange Plaza, Ayala Triangle, Ayala Avenue, Makati City', 'corporate.popi@primeorion.com.ph', '884-1106');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (213, 'Primetown Property Group, Inc.', 'UNIT 2807, Century Citadel Inn Makati 5007 P. Burgos St., Makati City', 'sva_ppgi@yahoo.com', '751-1957');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (214, 'Primex Corporation', 'G/F Richbelt Terraces, 19 Annapolis St., Greenhills, San Juan, Manlla', ' prx@skyinet.net', '(02) 722-8078');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (215, 'Pryce Corporation', '17/F Pryce Center 1179 Chino Roces Ave. Cor. Bagtikan St., Makati City', 'epe@pryce.com.ph', '(+632) 899-4401');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (216, 'Puregold Price Club, Inc.', 'No. 900 Romualdez Street, Paco, Manila', 'customerservice@puregold.com.ph', '523-3055');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (217, 'RFM Corporation', 'RFM Corporate Center, Pioneer Corner Sheridan Streets, Mandaluyong City, 1550', ' rfmmail@rfm.com.ph', '631-8101');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (218, 'Republic Glass Holdings Corporation', '6/F, Republic Glass Building 196 Salcedo St., Legaspi Village Makati City 1200', ' fcw@rghc.net', '817-5011 to 13');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (219, 'Rizal Commercial Banking Corporation', '12/F Yuchengco Tower, RCBC Plaza, 6819 Ayala Ave. cor. Sen. Gil. J. Puyat Ave., Makati City 1200', ' webmaster@rcbc.com', '894-9000');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (220, 'Robinsons Land Corporation', '43/F Robinsons Equitable Tower, ADB Avenue corner Poveda St., Ortigas Center, Pasig City', ' info@robinsonsland.com', '397-1888');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (221, 'Robinsons Retail Holdings, Inc.', '43rd Floor, Robinsons Equitable Tower, ADB Avenue corner Poveda Sts., Ortigas Center, Pasig City, Metro Manila', 'info@robinsonsretailholdings.com.ph', '(632) 635 0751 to 64');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (222, 'Rockwell Land Corporation', '2F, 8 Rockwell, Hidalgo Drive, Rockwell Center, Makati City', 'inquire@rockwell.com.ph', '632) 7930088');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (223, 'Roxas Holdings, Inc.', '14th Floor, Net One Center, 26th Street corner 3rd Avenue, Bonifacio Global City, Taguig, Metro Manila, 1634 Philippines', 'florencio.mamauag@rhi.com.ph', '771-7800 to 05');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (224, 'Roxas and Company, Inc.', '7th Floor, Cacho Gonzales Building, 101 Aguirre Street, Legaspi Village, 1229 Makati City', 'boy.mamauag@cadp.com.ph', '810-8901 to 06');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (225, 'SBS Philippines Corporation', 'No. 10 Resthaven Street, San Francisco Del Monte, Quezon City', 'info@sytengco.com ', '(02) 371 1111');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (226, 'SFA Semicon Philippines Corporation', 'Panday Pira Avenue cor. Creekside Road Clark Freeport Zone Pampanga, Philippines', 'ssphr@sfasemicon.com', '045-499-1742 ');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (227, 'SM Investments Corporation', '10th Flr, OneE-com Center, Harbor Drive, Mall of Asia Complex, CBP-1, Pasay City', 'info@sminvestments.com', '857-0100');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (228, 'SM Prime Holdings, Inc.', 'Mall of Asia Arena Annex Building, Coral Way cor. J.W. Diokno Blvd., Mall of Asia Complex, Brgy. 76, Zone 10, CBP-1A, 1300 Pasay', ' info@smprime.com', '(632) 831-1000');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (229, 'SOCResources, Inc.', 'Enzo Building, 399 Senator Gil Puyat Avenue, Makati City', 'socinfo@southchinaresourcesinc.com.ph', '892-2049');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (230, 'SPC Power Corporation', '7th Floor, Cebu Holdings Center, Archbishop Reyes Avenue, Cebu Business Park, Cebu City', 'spc@unet.net.ph', '(632) 8104474 to 77');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (231, 'SSI Group, Inc.', '6/F Midland Buendia Building, 403 Senator Gil Puyat Avenue, Makati City 1200', 'info.ssi@rgoc.com.ph', '(632) 890-8034');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (232, 'STI Education Systems Holdings, Inc.', '7th Floor, STI Holdings Center, 6764 Ayala Avenue, Makati City 1226', 'info@stiholdings.com', '844-9553');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (233, 'San Miguel Corporation', '40 San Miguel Avenue, Mandaluyong City, 1550 Metro Manila, Philippines', 'smcl@sanmiguel.com.ph', '632-3000');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (234, 'San Miguel Pure Foods Company, Inc.', '23rd Floor, JMT Building, ADB Ave., Ortigas Center, Pasig City', 'customercare.corporate@smg.sanmiguel.com.ph ', '702-5000');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (235, 'Seafront Resources Corporation', '7/F, JMT Condominium Bldg. ADB Ave., Ortigas Center, Pasig City 1600', 'seafront@broline.com', '637-2917 / 4032 / 4362 / 5799');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (236, 'Security Bank Corporation', 'Security Bank Centre 6776 Ayala Ave., Makati City 0719', ' corsec@securitybank.com.ph', '867-6788');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (237, 'Semirara Mining and Power Corporation', '2/F DMCI Bldg. 2281 Pasong Tamo Extension Makati City', 'hotline@semirarampc.com', '888-3000');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (238, 'Shakey''s Pizza Asia Ventures, Inc.', 'Km 15 East Service Road corner Marian Road 2, Tindalo Street, Barangay San Martin de Porres, Paranaque City', 'WeCare@shakeys.biz', '(632) 867 7677');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (239, 'Shang Properties, Inc.', 'Administration Office, Shangri-La Plaza Mall, EDSA corner Shaw Boulevard, Mandaluyong City', 'bobong@kuokphil.com', '635-83-00');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (240, 'Solid Group, Inc.', '2/F Solid House, 2285 Chino Roces Ave. (formerly Pasong Tamo Ext.), Makati City 1231', 'info@solidgroup.com.ph', '843-1511');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (241, 'Splash Corporation', '5/F W-Office Building 28th St. corner 11th Avenue , Bonifacio Global City, Taguig City', 'splashcare@splashcorp.com', '(02) 491-77-07 loc 1324');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (242, 'Sta. Lucia Land, Inc.', 'Penthouse Building III, Sta. Lucia Mall, Marcos Highway corner Imelda Avenue, Cainta, Rizal', 'investorsli@stalucialand.com.ph', '681-7332');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (243, 'Starmalls, Inc.', '3rd Level Starmall Las Piñas, CV Starr Avenue, Philamlife Village, Pamplona, Las Piñas City', 'investor.relations@starmalls.com.ph', '871-4001');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (244, 'Steniel Manufacturing Corporation', 'Gateway Business Park, Brgy. Javalera, General Trias, Cavite', ' gdg@steniel.com.ph', '(046) 433-0066');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (245, 'Sun Life Financial Inc.', '15/F Tower II, The Enterprise Center, 6766 Ayala Ave. cor. Paseo de Roxas, Makati City', ' phil.csd@sunlife.com', '886-6188 loc. 8620');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (246, 'Suntrust Home Developers, Inc.', '6/F The World Centre, 330 Sen. Gil J. Puyat Ave., Makati City 1227', 'budget@megaworld.com', '867-8826 to 40');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (247, 'Supercity Realty Development Corporation', '41st Floor Joy Nostalg Center, No. 17 Adb Avenue Ortigas Center, Pasig City', 'rickycunanan@supercity.com.ph', '638-7779');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (248, 'Swift Foods, Inc.', '4F RFM Corporate Center, Sheridan Cor. Pioneer St., Mandaluyong City', 'agri.hrd@swiftfoods.com.ph', '631-8101');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (249, 'Synergy Grid & Development Phils., Inc.', '1/F Corporate Business Center, 151 Paseo de Roxas, Makati City', 'lsmagpantay@crc.com.ph', '892-0231');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (250, 'TKC Metals Corporation', '2nd Floor W Tower Condominium 39th St., North Bonifacio Triangle, Bonifacio Global City, Taguig', 'corporateservices@tkcmetals.com.ph', '864-0734');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (251, 'The Philippine Stock Exchange, Inc.', 'Philippine Stock Exchange Plaza, Ayala Triangle, Ayala Avenue, Makati City', 'pird@pse.com.ph', '688-7600');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (252, 'The Philodrill Corporation', '8th Floor, Quad Alpha Centrum, 125 Pioneer Street, Mandaluyong City, Philippines', 'info@philodrill.com', '(632) 6318151/52');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (253, 'Top Frontier Investment Holdings, Inc.', '5th Floor, ENZO Building, 399 Sen. Gil Puyat Avenue, Makati City', 'mrbalanza@smg.sanmiguel.com.ph', '632-3431');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (254, 'Transpacific Broadband Group Int`l. Inc.', '9/F Summit One Tower, 530 Shaw Boulevard, Mandaluyong City 1550', 'info@tbgi.net.ph', '(02) 717-0523');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (255, 'Travellers International Hotel Group, Inc.', '10/F Newport Entertainment & Commercial Centre, Newport Boulevard, Newport City, Pasay City, Metro Manila', 'investor.relations@rwmanila.com.ph', '+632 908 8000');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (256, 'Unioil Resources & Holdings Company, Inc.', '6th Floor Sagittarius Building, 111 HV dela Costa Street, Salcedo Village, Makati City, Philippines', null, '892-7002');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (257, 'Union Bank of the Philippines, Inc.', 'UnionBank Plaza, Meralco Avenue Corner Onyx & Sapphire Roads, Ortigas Center, Pasig City 1605', 'customer.service@unionbankph.com', '667-6388');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (258, 'United Paragon Mining Corporation', '5F Quad Alpha Centrum Bldg., 125 Pioneer St., Mandaluyong City', '
upmcmnl@globelines.com.ph', '(632) 636-5133 to 34');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (259, 'Universal Robina Corporation', '43/F Robinsons Equitable Tower, ADB Avenue corner Poveda Street, Ortigas Center, Pasig City', 'URC-CustomerCare@JGSummit.net', '
(632) 633-7631 to 40');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (260, 'Vantage Equities, Inc.', 'Units 2004-2005 East Tower PSE Centre, Exchange Road, Ortigas Center, Pasig City ', 'investor@ivantage.ph', '689-8090 to 93');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (261, 'Victorias Milling Company, Inc.', 'VMC Compound, J. J. Ossorio St. Barangay XVI, Victorias City Negros Occidental', 'jllamas@info.com', '(034)399-2717');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (262, 'Vista Land & Lifescapes, Inc.', 'City Registered Address: 3rd Level Starmall Las Piñas, CV Starr Avenue, Pamplona, Las Piñas City / Business Address: UGF Worldwi', 'ir@vistaland.com.ph', '+63 2 584-5308');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (263, 'Vitarich Corporation', 'San Jose Road, Sta. Rosa 1, Marilao Bulacan', ' info@vitarich.com', '044) 815-6117 to 6119');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (264, 'Vivant Corporation', 'Unit 907-908 9th floor Ayala Life-FGU Center, Stock Transfer Agent Cebu Business Park, Cebu City, Mindanao Avenue corner Biliran', 'info@vivant.com.ph', '(032) 234-2256');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (265, 'Vulcan Industrial & Mining Corporation', '9/F Quad Alpha Centrum, 125 Pioneer St., Mandaluyong City', 'info@vulcanminingcorp.com', '631-5139');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (266, 'Waterfront Philippines, Incorporated', '7th Floor Manila Pavilion Hotel, United Nations Avenue corner Ma. Orosa Street Manila', 'whcco@waterfronthotels.net.', '559-0888');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (267, 'Wellex Industries, Incorporated', '35th Floor, One Corporate center, Dona Julia Vargas Avenue corner Meralco Avenue, Ortigas Center, Pasig City, Metro Manila', 'info@wellex.com.ph', '(02) 706-7888');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (268, 'Wilcon Depot, Inc.', 'No. 90 E. Rodriguez Jr. Avenue, Ugong Norte, Quezon City', 'investor_relations@wilcon.com.ph', '(02) 634-8387');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (269, 'Xurpas Inc.', '7th Floor, Cambridge Centre, 108 Tordesillas St., Salcedo Village, Makati City 1227', null, '(632) 889-6467');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (270, 'Zeus Holdings, Inc.', '20/F LKG Tower, 6801 Ayala Avenue, Makati City 1226', 'webmaster@zeusholdingsinc.com ', '884-1106');
INSERT INTO jackfruit.companies (id, name, address, email, phone) VALUES (271, 'iPeople, inc.', '3/F Grepalife Building, 219 Sen. Gil J. Puyat Ave., Makati City 1200', ' jalabast@mozcom.com', '815-96-36');